apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "3000"
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: kpop_store_db
  DB_USERNAME: postgres
  JWT_SECRET: mi_clave_secreta_kpop_store
  JWT_EXPIRES_IN: 1d

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_PASSWORD: "123456"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpop-backend
  template:
    metadata:
      labels:
        app: kpop-backend
    spec:
      containers:
        - name: backend
          image: kpop-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: kpop-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort